# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           :slug

# Setup
title:               'رادیو دال | Radio Daal'
fa_title:            'رادیو دال'
tagline:             'این پادکست یک مرجع نیست، یک تجربه است.'
description:         'در این پادکست آرش به دنبال جواب سوالاتی که دارد و یا برای شنیدن یک داستان جذاب با آدم‌های مختلف هم‌صحبت می‌شود.'
subtitle:            'مگه این نیست هرکدوم تا آخر عمر یه تعداد محدودی واژه میتونیم بگیم و بنویسیم و تایپ کنیم؟ پس بهتر نیست از این واژه ها به بهترین نحو ممکن استفاده کنیم و کلماتمون را تا جایی که میشه با افراد بیشتری به اشتراک بذاریم؟'
url:                 https://radioDaal.arashTaher.com
baseurl:             ''
paginate:            5
lang:                'fa'
copyright:           "&#x2117; &amp; &#xA9; 2019"
timezone:            "Asia/Tehran"

# About/contact
author:
  name:              Arash Taher
  url:               https://arashTaher.com
  email:             radioDaalPodcast@gmail.com

# Custom vars
version:             1.0.0

include: [_redirects]

plugins:
    - jekyll-paginate
    - jalalidate

# Front Matter Defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      excerpt_separator: <!-- more -->
